[font]
# normal = ["Monaspace Neon"]
normal = ["Fira Code"]
size = 16

# [font.features]
# "Monaspace Neon" = ["+calt", "+liga", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08", "+ss09"]